name = "SimpleUpdate"
uuid = "8aee75b1-ae64-4a42-a794-ac82a951fe6d"
authors = ["Finn Krein <finn@krein.moe>"]
version = "0.1.0"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
